### ISSUE TITLE
Clicking `Preview` from the CMS on a `Blog Post` after deploying a site does not properly resolve the URL, results in a 404

### ISSUE THREAD

**Issue by jamesvidler** [agility/agilitycms-eleventy-starter#5]
![image](https://user-images.githubusercontent.com/12719665/122419383-dc002200-cf58-11eb-9b05-d375804e596d.png)

**Comment by joshua-isaac** [comment]
@jamesvidler cms previews are not currently supported in eleventy, we have articles on how to set up preview deployments on both netlify and vercel:

netlify: https://help.agilitycms.com/hc/en-us/articles/360061064432

vercel: https://help.agilitycms.com/hc/en-us/articles/360061588511
